In [78]:
import numpy as np
from itertools import product
from itertools import combinations

4.1 Написать функцию формирования порождающей и проверочной матриц расширенного кода Голея (24,12,8)

In [32]:
# Расширенный код Голея
B = np.array([
    [1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
    [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
    [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
    [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
    [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
    [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
    [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
    [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
    [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
    [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])

In [33]:
def golay_24_12_8_matrices(B):
    I = np.eye(12, dtype=int)  # Единичная матрица 12x12
    G = np.hstack((I, B))  # [I | P]

    # Проверочная матрица H (12 x 24)
    H = np.hstack((B.T, I))  # [P^T | I]

    return G, H
G, H = golay_24_12_8_matrices(B)
print("Порождающая матрица G:")
print(G)
print("\nПроверочная матрица H:")
print(H)

Порождающая матрица G:
[[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]]

Проверочная матрица H:
[[1 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 0 1 1 1 1 0 0 0 0 

4.2. Провести исследование расширенного кода Голея для одно-, двух-, 
трёх- и четырёхкратных ошибок. 

In [34]:
def encode_message(message, G):
    return np.dot(message, G) % 2

def introduce_errors(codeword, num_errors):
    error_positions = np.random.choice(24, num_errors, replace=False)
    error_vector = np.zeros(24, dtype=int)
    error_vector[error_positions] = 1
    return (codeword + error_vector) % 2

def decode_message(received, H):
    syndrome = np.dot(received, H.T) % 2
    if np.all(syndrome == 0):
        return received[:12]

    # Проверка на однократную ошибку
    for i in range(24):
        if np.array_equal(syndrome, H[:, i]):
            received[i] = (received[i] + 1) % 2
            return received[:12]

    # Проверка на двукратную ошибку
    for i, j in combinations(range(24), 2):
        if np.array_equal(syndrome, (H[:, i] + H[:, j]) % 2):
            received[i] = (received[i] + 1) % 2
            received[j] = (received[j] + 1) % 2
            return received[:12]

    # Проверка на трехкратную ошибку
    for i, j, k in combinations(range(24), 3):
        if np.array_equal(syndrome, (H[:, i] + H[:, j] + H[:, k]) % 2):
            received[i] = (received[i] + 1) % 2
            received[j] = (received[j] + 1) % 2
            received[k] = (received[k] + 1) % 2
            return received[:12]

    # Если ошибка не обнаружена, возвращаем исходное сообщение
    return received[:12]

def test_error_correction(num_tests, num_errors):
    success = 0
    for _ in range(num_tests):
        message = np.random.randint(2, size=12)
        codeword = encode_message(message, G)
        received = introduce_errors(codeword, num_errors)
        decoded = decode_message(received, H)
        if np.array_equal(message, decoded):
            success += 1
    return success / num_tests

In [35]:
# Проведем тестирование
num_tests = 10000
for errors in range(1, 5):
    success_rate = test_error_correction(num_tests, errors)
    print(f"Успешность исправления {errors}-кратных ошибок: {success_rate:.2%}")

Успешность исправления 1-кратных ошибок: 100.00%
Успешность исправления 2-кратных ошибок: 100.00%
Успешность исправления 3-кратных ошибок: 100.00%
Успешность исправления 4-кратных ошибок: 4.68%


4.3 Написать функцию формирования порождающей и проверочных 
матриц кода Рида-Маллера 𝑅𝑀(𝑟,𝑚) на основе параметров 𝑟 и 𝑚. 

In [79]:
def G_RM(r, m):
    if 0 < r < m:
        leftup = G_RM(r, m - 1)
        rightlow = G_RM(r - 1, m - 1)
        return np.hstack([np.vstack([leftup, np.zeros((len(rightlow), len(leftup.T)), int)]),
                          np.vstack([leftup, rightlow])])
    elif r == 0:
        return np.ones((1, 2 ** m), dtype=int)
    elif r == m:
        up = G_RM(m - 1, m)
        low = np.zeros((1, 2 ** m), dtype=int)
        low[0][len(low.T) - 1] = 1
        return np.vstack([up, low])

In [80]:
r, m = 1, 3
G =  G_RM(r, m)

print("Порождающая матрица G:")
print(G)

Порождающая матрица G:
[[1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]]


4.4 Провести исследование кода Рида-Маллера 𝑅𝑀(1,3) для одно- и 
двукратных ошибок.

In [81]:
def encode(message, G):
    return np.dot(message, G) % 2

def add_errors(codeword, num_errors):
    n = len(codeword)
    error_positions = np.random.choice(n, num_errors, replace=False)
    error_vector = np.zeros(n, dtype=int)
    error_vector[error_positions] = 1
    return (codeword + error_vector) % 2

def decode(received, G):
    n = G.shape[1]
    k = G.shape[0]
    all_codewords = [encode(msg, G) for msg in np.array(list(product([0, 1], repeat=k)))]

    min_distance = float('inf')
    decoded_codeword = None

    for codeword in all_codewords:
        distance = np.sum(codeword != received)
        if distance < min_distance:
            min_distance = distance
            decoded_codeword = codeword

    return decoded_codeword

def test_error_correction(r, m, num_errors, num_tests=1000):
    G = G_RM(r, m)
    k = G.shape[0]
    n = G.shape[1]

    success_count = 0

    for _ in range(num_tests):
        message = np.random.randint(2, size=k)
        codeword = encode(message, G)
        received = add_errors(codeword, num_errors)
        decoded = decode(received, G)

        if np.array_equal(codeword, decoded):
            success_count += 1

    success_rate = success_count / num_tests
    print(f"RM({r},{m}) с {num_errors} ошибками: Успешно исправлено {success_rate:.2%}")


In [82]:
print("Тестирование RM(1,3):")
test_error_correction(1, 3, 1)
test_error_correction(1, 3, 2)

Тестирование RM(1,3):
RM(1,3) с 1 ошибками: Успешно исправлено 100.00%
RM(1,3) с 2 ошибками: Успешно исправлено 25.30%


In [83]:
print("\nТестирование RM(1,4):")
test_error_correction(1, 4, 1)
test_error_correction(1, 4, 2)
test_error_correction(1, 4, 3)
test_error_correction(1, 4, 4)


Тестирование RM(1,4):
RM(1,4) с 1 ошибками: Успешно исправлено 100.00%
RM(1,4) с 2 ошибками: Успешно исправлено 100.00%
RM(1,4) с 3 ошибками: Успешно исправлено 100.00%
RM(1,4) с 4 ошибками: Успешно исправлено 44.80%
